name: terra_mystica_models
channels:
  - conda-forge
dependencies:
  - flake8
  - pip
  - ipython
  - jupyterlab
  - ipywidgets
  - nodejs
  - widgetsnbextension
  - altair
  - seaborn
  - numpy
  - pandas
  - pandas-profiling
  - scikit-learn
  - statsmodels
  - black
  - pre_commit
  - beautifulsoup4
  - requests
  - pip:
    - python-dotenv
    - -e .